project:
  type: website

website:
  # title: "website"
  search: false
  navbar:
    left:
      - index.qmd
    right:
      - icon: github
        href: https://github.com/lweitkamp/
      - icon: twitter
        href: https://twitter.com/laurensweitkamp
format:
  html:
    highlight-style: pygments
    code-overflow: scroll # wrap
    fontsize: 15px
    theme: litera  # litera sandstone
    css: styles.css

execute:
  freeze: auto
