project:
  type: website

website:
  search: false
  navbar:
    left:
      - index.qmd
    right:
      - icon: github
        href: https://github.com/lweitkamp/
      - icon: twitter
        href: https://twitter.com/laurensweitkamp
format:
  html:
      grid: 
        margin-width: 350p
      highlight-style: nord
  # html:
    # linkcolor: "#FF5733"
    # theme: litera  # litera sandstone
    # css: styles.css
    # highlight-style: pygments

execute:
  freeze: auto