baseURL: http://example.org/
languageCode: en-us
title: Laurens Weitkamp
theme: "PaperMod"

params:
    math: true

    # social media metadata
    env: production

    # ShowBreadCrumbs: true
    homeInfoParams:
        Title: Work In Progress 🔧
        Content: ...

    # Table of content stuff
    ShowToc: true
    TocOpen: true

    # Social Icons on main page
    socialIcons:
      - name: "twitter"
        title: "Twitter"
        url: "https://twitter.com/laurensweitkamp"
      - name: "github"  
        title: "GitHub"
        url: "https://github.com/lweitkamp"
    
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: gruvbox-light
        #lineNos: false


# Menu
menu:
  main:
    - identifier: Post Archive
      name: Post Archive
      url: /posts/
      weight: 10
    - identifier: Optimizing Transformers Series
      name: Optimizing Transformers Series
      url: /optimizing_transformers/
      weight: 20