baseURL: https://lweitkamp.github.io
languageCode: en-us
title: Eigenvalues in Bloom
theme: "etch"

params:

    hideSummary: true
    
    math: true

    # social media metadata
    env: production


    # Table of content stuff
    ShowToc: true
    TocOpen: true

    # Social Icons on main page
    socialIcons:
      - name: "twitter"
        title: "Twitter"
        url: "https://twitter.com/laurensweitkamp"
      - name: "github"  
        title: "GitHub"
        url: "https://github.com/lweitkamp"
    
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        lineNumbersInTable: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokailight



# Menu
menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 1
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: Triton Primer
      name: Triton Primer
      url: /triton_exercises/
      weight: 3
